name: CI

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t ${{ vars.REGISTRY }}/frontend:latest .

      - name: Push image
        run: docker push ${{ vars.REGISTRY }}/frontend:latest

  cleanup:
    needs: [ release ]
    runs-on: self-hosted

    steps:
      - name: Cleanup image
        run: docker rmi ${{ vars.REGISTRY }}/frontend:latest