name: CI

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t ${{ vars.REGISTRY }}/frontend:latest .

      - name: Push image
        run: docker push ${{ vars.REGISTRY }}/frontend:latest